In [2]:
import pandas as pd

# URL of the CSV file (example)
url = "https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2024-25/gws/merged_gw.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(url)
df

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Alex Scott,MID,Bournemouth,1.6,0,0,11,0,12.8,77,...,1,0.0,2,0,0,0,50,False,0,1
1,Carlos Miguel dos Santos Pereira,GK,Nott'm Forest,2.2,0,0,0,0,0.0,427,...,1,0.0,0,0,0,0,45,True,0,1
2,Tomiyasu Takehiro,DEF,Arsenal,0.0,0,0,0,0,0.0,22,...,2,0.0,0,0,0,0,50,True,0,1
3,Malcolm Ebiowei,MID,Crystal Palace,0.0,0,0,0,0,0.0,197,...,2,0.0,0,0,0,0,45,False,0,1
4,Ben Brereton Díaz,MID,Southampton,1.0,0,0,-2,0,14.0,584,...,1,16.0,1,0,0,0,55,False,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6547,Giovani Lo Celso,MID,Spurs,0.0,0,0,0,0,0.0,493,...,4,0.0,0,-90,0,90,49,True,0,10
6548,Tawanda Chirewa,MID,Wolves,0.0,0,0,0,0,0.0,538,...,2,0.0,0,-196,0,196,45,True,0,10
6549,Cameron Humphreys,MID,Ipswich,0.0,0,0,0,0,0.0,273,...,1,0.0,0,-103,0,103,45,True,0,10
6550,Ashley Young,DEF,Everton,5.2,0,0,6,0,32.4,238,...,1,2.0,2,57104,60867,3763,45,False,0,10
6551,James Bree,DEF,Southampton,-0.2,0,0,0,0,0.0,457,...,1,0.0,0,4050,4806,756,39,True,0,10

In [3]:
import pandasql
from pandasql import sqldf
pysqldf = lambda q: sqldf(q, globals())

In [4]:
df['form'] = df['total_points'].rolling(window=5).mean()

dfFWD = df[df['position'] == 'FWD']
dfMID = df[df['position'] == 'MID']
dfDEF = df[df['position'] == 'DEF']
dfGK = df[df['position'] == 'GK']
dfHaaland = df[df['name'] == 'Erling Haaland']
dfHaaland

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,...,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,form
232,Erling Haaland,FWD,Man City,5.0,0,2,31,1,0.6,351,...,38.0,7,0,0,0,150,False,1,1,3.6
851,Erling Haaland,FWD,Man City,13.5,0,3,80,0,3.3,351,...,83.0,17,222715,275319,52604,150,True,0,2,4.8
1484,Erling Haaland,FWD,Man City,14.7,0,3,93,0,11.1,351,...,66.0,17,566889,642719,75830,151,False,0,3,4.0
2135,Erling Haaland,FWD,Man City,10.9,0,3,58,0,1.5,351,...,85.0,13,684275,791306,107031,152,True,0,4,3.2
2794,Erling Haaland,FWD,Man City,14.0,0,3,33,0,0.5,351,...,114.0,9,274627,329275,54648,153,True,0,5,4.0
3456,Erling Haaland,FWD,Man City,8.5,0,0,12,0,12.3,351,...,57.0,2,258724,286015,27291,153,False,0,6,1.6
4120,Erling Haaland,FWD,Man City,7.5,0,0,10,0,23.6,351,...,42.0,2,59763,132448,72685,154,True,0,7,0.8
4786,Erling Haaland,FWD,Man City,3.0,0,0,6,0,13.2,351,...,8.0,2,47225,110645,63420,154,False,0,8,0.8
5454,Erling Haaland,FWD,Man City,4.8,0,0,26,1,2.0,351,...,91.0,6,5336,77692,72356,154,True,0,9,2.0
6126,Erling Haaland,FWD,Man City,4.3,0,0,-1,0,0.6,351,...,69.0,2,-178318,39141,217459,154,False,0,10,0.6

In [5]:
#cleaning1 = """SELECT * FROM df
#where name = 'Erling Haaland' ;"""

#df = pysqldf(cleaning1)
#df

list(df.columns.values)

['name',
 'position',
 'team',
 'xP',
 'assists',
 'bonus',
 'bps',
 'clean_sheets',
 'creativity',
 'element',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals',
 'expected_goals_conceded',
 'fixture',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'influence',
 'kickoff_time',
 'minutes',
 'opponent_team',
 'own_goals',
 'penalties_missed',
 'penalties_saved',
 'red_cards',
 'round',
 'saves',
 'selected',
 'starts',
 'team_a_score',
 'team_h_score',
 'threat',
 'total_points',
 'transfers_balance',
 'transfers_in',
 'transfers_out',
 'value',
 'was_home',
 'yellow_cards',
 'GW',
 'form']

In [17]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pandas as pd

In [30]:

def RegModel(dfinput):

    X = dfinput.drop(columns=['total_points', 'name', 'position', 'team', 'kickoff_time'])  # Drop the target column to get predictors
    y = dfinput['total_points']                 # Target variable
    # Example: Splitting data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize the model
    rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
    rf_model.fit(X_train, y_train)

    # Get feature importances
    feature_importances = rf_model.feature_importances_
    importance_df = pd.DataFrame({
        'Feature': X.columns,
        'Importance': feature_importances
    }).sort_values(by='Importance', ascending=False)

    # Display the most important features
    # print(importance_df)

    top_features = importance_df['Feature'].head(5).tolist()
    X_train_top = X_train[top_features]
    X_test_top = X_test[top_features]

    

    # Example: Training a linear regression model with the top features
    final_model = LinearRegression()
    final_model.fit(X_train_top, y_train)

    # Evaluate on the test set
    y_pred = final_model.predict(X_test_top)
    return final_model, X_test_top, y_test, y_pred, importance_df

RegFWD = RegModel(dfFWD)
RegMID = RegModel(dfMID)
RegDEF = RegModel(dfDEF)
RegGK = RegModel(dfGK)

In [37]:
FWDimportance = RegFWD[4]
FWDimportance

MIDimportance = RegMID[4]
MIDimportance

DEFimportance = RegDEF[4]
DEFimportance

GKimportance = RegGK[4]
GKimportance

                       Feature  Importance
3                          bps    0.757931
4                 clean_sheets    0.134558
2                        bonus    0.041956
23                       saves    0.014835
20             penalties_saved    0.010162
14                   ict_index    0.009458
15                   influence    0.006617
12              goals_conceded    0.005520
10     expected_goals_conceded    0.003056
36                        form    0.002556
0                           xP    0.001656
6                      element    0.001535
29           transfers_balance    0.001131
24                    selected    0.001058
34                yellow_cards    0.001029
26                team_a_score    0.000982
11                     fixture    0.000925
31               transfers_out    0.000921
30                transfers_in    0.000711
17               opponent_team    0.000674
32                       value    0.000544
1                      assists    0.000521
22                       round    0.000419
35                          GW    0.000361
16                     minutes    0.000247
27                team_h_score    0.000209
33                    was_home    0.000098
7             expected_assists    0.000089
25                      starts    0.000087
8   expected_goal_involvements    0.000086
18                   own_goals    0.000034
5                   creativity    0.000021
28                      threat    0.000008
9               expected_goals    0.000004
21                   red_cards    0.000000
13                goals_scored    0.000000
19            penalties_missed    0.000000

In [39]:
def testing(TestModel, X_test_top, y_test, y_pred):

    from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
    import numpy as np

    # Predict on test set
    y_pred = TestModel.predict(X_test_top)

    # Calculate evaluation metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print(f"MAE: {mae}")
    print(f"RMSE: {rmse}")
    print(f"R^2: {r2}")
    return 

testing(RegFWD[0], RegFWD[1], RegFWD[2], RegFWD[3])

testing(RegMID[0], RegMID[1], RegMID[2], RegMID[3])

testing(RegDEF[0], RegDEF[1], RegDEF[2], RegDEF[3])

testing(RegGK[0], RegGK[1], RegGK[2], RegGK[3])

MAE: 0.331099061554645
RMSE: 0.5471966383227933
R^2: 0.9726230993700978
MAE: 0.4560741652421713
RMSE: 0.7456643918190564
R^2: 0.9105914400497156
MAE: 0.35729703742086694
RMSE: 0.6236109960881181
R^2: 0.8962468490479034
MAE: 0.2078693213129495
RMSE: 0.407526403118533
R^2: 0.9685060893600546